apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishub2aks-e855"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishub2aks-e855"
  template:
    metadata:
      labels:
        app: "aatiwarishub2aks-e855"
    spec:
      containers:
        - name: "aatiwarishub2aks-e855"
          image: "kapasrijkubacr.azurecr.io/aatiwarishub2akse855"
          ports:
          - containerPort: 8080