apiVersion : apps/v1
kind: Deployment
metadata:
  name: "democluster-7b64"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "democluster-7b64"
  template:
    metadata:
      labels:
        app: "democluster-7b64"
    spec:
      containers:
        - name: "democluster-7b64"
          image: "kapasrijkubacr.azurecr.io/democluster7b64"
          ports:
          - containerPort: 8080