apiVersion: v1
kind: Service
metadata:
    name: "democluster-7b64"
    labels:
        app: "democluster-7b64"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "democluster-7b64"